// Inline (sitede tıklayarak) düzenlenen tüm içerik anahtarlarının admin karşılığı.
// İletişim/kargo/saatler/sosyal/SEO/e-posta zaten ayrı sayfalarda — burada yok.

export type FieldType = "text" | "textarea" | "image";
export type Field = { key: string; label: string; type?: FieldType; def: string };
export type Section = { title: string; note?: string; fields: Field[] };

export const SECTIONS: Section[] = [
  {
    title: "Logo & Marka",
    fields: [
      { key: "logo_name_part1", label: "Logo Metni (1)", def: "Galaksi" },
      { key: "logo_name_part2", label: "Logo Metni (2 — altın)", def: "Motor" },
      { key: "logo_image_url", label: "Logo Görseli", type: "image", def: "/logos/galaksi-motor-logo.jpg" },
    ],
  },
  {
    title: "Menü (Navbar)",
    fields: [
      { key: "nav_home", label: "Anasayfa", def: "Anasayfa" },
      { key: "nav_urunler", label: "Ürünler", def: "Ürünler" },
      { key: "nav_bakim", label: "Bakım", def: "Bakım" },
      { key: "nav_randevu", label: "Randevu", def: "Randevu" },
      { key: "nav_auth_account", label: "Hesabım", def: "Hesabım" },
      { key: "nav_auth_login", label: "Giriş", def: "Giriş" },
      { key: "nav_auth_register", label: "Kayıt Ol", def: "Kayıt Ol" },
      { key: "nav_auth_logout", label: "Çıkış", def: "Çıkış" },
      { key: "nav_auth_admin", label: "Admin", def: "Admin" },
    ],
  },
  {
    title: "Anasayfa — Hero (üst bölüm)",
    fields: [
      { key: "hero_badge", label: "Rozet", def: "Küçükçekmece'nin motosiklet üssü" },
      { key: "hero_title_1", label: "Başlık 1", def: "Motosikletinin" },
      { key: "hero_title_2", label: "Başlık 2", def: "Tüm İhtiyacı" },
      { key: "hero_title_3", label: "Başlık 3", def: "Bu Adreste!" },
      { key: "hero_subtitle", label: "Alt metin", type: "textarea", def: "Orijinal yedek parça, profesyonel bakım ürünleri ve şık aksesuarlar — uzman servis ekibiyle." },
      { key: "hero_cta_primary", label: "Birincil buton", def: "Ürünleri Keşfet" },
      { key: "hero_cta_secondary", label: "İkincil buton", def: "Servis Randevusu" },
      { key: "hero_scroll", label: "Aşağı kaydır metni", def: "Aşağı" },
      { key: "hero_stat_1_v", label: "İstatistik 1 — değer", def: "500+" },
      { key: "hero_stat_1_l", label: "İstatistik 1 — etiket", def: "Ürün" },
      { key: "hero_stat_2_v", label: "İstatistik 2 — değer", def: "1.5K+" },
      { key: "hero_stat_2_l", label: "İstatistik 2 — etiket", def: "Müşteri" },
      { key: "hero_stat_3_v", label: "İstatistik 3 — değer", def: "24h" },
      { key: "hero_stat_3_l", label: "İstatistik 3 — etiket", def: "Kargo" },
      { key: "hero_stat_4_v", label: "İstatistik 4 — değer", def: "10+" },
      { key: "hero_stat_4_l", label: "İstatistik 4 — etiket", def: "Yıl tecrübe" },
    ],
  },
  {
    title: "Anasayfa — Bölüm Başlıkları",
    fields: [
      { key: "sec_feat_badge", label: "Öne Çıkanlar — rozet", def: "· Öne Çıkanlar" },
      { key: "sec_feat_title", label: "Öne Çıkanlar — başlık", def: "En çok tercih edilenler" },
      { key: "sec_feat_sub", label: "Öne Çıkanlar — alt", type: "textarea", def: "Müşterilerimizin en çok tercih ettiği, stokta hazır ürünler." },
      { key: "sec_feat_cta", label: "Öne Çıkanlar — link", def: "Tüm ürünler" },
      { key: "sec_cat_badge", label: "Kategoriler — rozet", def: "· Kategoriler" },
      { key: "sec_cat_title", label: "Kategoriler — başlık", def: "İhtiyacın olan her şey," },
      { key: "sec_cat_accent", label: "Kategoriler — vurgu", def: "bir tık ötede" },
      { key: "sec_cat_cta", label: "Kategoriler — link", def: "Tümünü gör" },
      { key: "sec_why_badge", label: "Neden Biz — rozet", def: "· Neden Galaksi Motor?" },
      { key: "sec_why_title", label: "Neden Biz — başlık", def: "Yola güvenle çıkmanın" },
      { key: "sec_why_accent", label: "Neden Biz — vurgu", def: "3 sebebi" },
      { key: "sec_why_1_title", label: "Sebep 1 — başlık", def: "Orijinal Parça Garantisi" },
      { key: "sec_why_1_desc", label: "Sebep 1 — açıklama", type: "textarea", def: "Her ürün distribütör onaylı, faturalı ve değişim güvencesiyle gelir." },
      { key: "sec_why_2_title", label: "Sebep 2 — başlık", def: "Aynı Gün Kargo" },
      { key: "sec_why_2_desc", label: "Sebep 2 — açıklama", type: "textarea", def: "16:00'a kadar verilen siparişler aynı gün kargoya teslim edilir." },
      { key: "sec_why_3_title", label: "Sebep 3 — başlık", def: "Uzman Servis Ekibi" },
      { key: "sec_why_3_desc", label: "Sebep 3 — açıklama", type: "textarea", def: "10+ yıl tecrübeli ustalarımızla bakım ve tamir hizmeti." },
      { key: "sec_test_badge", label: "Yorumlar — rozet", def: "· Müşterilerimiz ne diyor?" },
      { key: "sec_test_title", label: "Yorumlar — başlık", def: "Binlerce" },
      { key: "sec_test_accent", label: "Yorumlar — vurgu", def: "mutlu sürücü" },
      { key: "sec_blog_badge", label: "Blog — rozet", def: "· Blog & Rehber" },
      { key: "sec_blog_title", label: "Blog — başlık", def: "Uzmanlarımızdan" },
      { key: "sec_blog_accent", label: "Blog — vurgu", def: "tavsiyeler" },
      { key: "sec_blog_cta", label: "Blog — link", def: "Tüm yazılar" },
      { key: "sec_faq_badge", label: "SSS — rozet", def: "· Sıkça sorulanlar" },
      { key: "sec_faq_title", label: "SSS — başlık", def: "Aklındaki" },
      { key: "sec_faq_accent", label: "SSS — vurgu", def: "soru burada" },
      { key: "sec_faq_cta", label: "SSS — link", def: "Tüm sorular" },
      { key: "sec_cta_badge", label: "Randevu CTA — rozet", def: "Servis randevusu" },
      { key: "sec_cta_title", label: "Randevu CTA — başlık", def: "Motorun bakım" },
      { key: "sec_cta_accent", label: "Randevu CTA — vurgu", def: "vakti gelmiş olabilir." },
      { key: "sec_cta_desc", label: "Randevu CTA — açıklama", type: "textarea", def: "Online randevu sistemiyle sıra beklemeden, dakikalar içinde gününü ayarla. Uzman ekibimiz seni karşılasın." },
      { key: "sec_cta_button", label: "Randevu CTA — buton", def: "Hemen Randevu Al" },
    ],
  },
  {
    title: "Anasayfa — İstatistik Şeridi",
    fields: [
      { key: "about_stat1_num", label: "1 — sayı", def: "10+" },
      { key: "about_stat1_desc", label: "1 — açıklama", def: "Yıllık tecrübe" },
      { key: "about_stat2_num", label: "2 — sayı", def: "500+" },
      { key: "about_stat2_desc", label: "2 — açıklama", def: "Stoktaki ürün" },
      { key: "about_stat3_num", label: "3 — sayı", def: "1.500+" },
      { key: "about_stat3_desc", label: "3 — açıklama", def: "Memnun müşteri" },
    ],
  },
  {
    title: "Atölye Fotoğrafı & Kategori Kartı",
    fields: [
      { key: "workshop_photo_url", label: "Atölye fotoğrafı", type: "image", def: "" },
      { key: "workshop_badge", label: "Atölye — rozet", def: "" },
      { key: "workshop_caption", label: "Atölye — açıklama", type: "textarea", def: "" },
      { key: "cat_cta", label: "Kategori kartı buton metni", def: "Keşfet" },
    ],
  },
  {
    title: "Footer",
    fields: [
      { key: "footer_brand_desc", label: "Marka açıklaması", type: "textarea", def: "Küçükçekmece İnönü Mahallesi'nde motosikletinizin ihtiyacı olan orijinal yedek parça, bakım ürünü ve aksesuarlar — uzman servis ekibiyle." },
      { key: "footer_col1_title", label: "Sütun 1 — başlık", def: "Mağaza" },
      { key: "footer_col1_l1", label: "Sütun 1 — link 1", def: "Tüm Ürünler" },
      { key: "footer_col1_l3", label: "Sütun 1 — link 3", def: "Bakım & Tamir" },
      { key: "footer_col1_l4", label: "Sütun 1 — link 4", def: "Aksesuarlar" },
      { key: "footer_col2_title", label: "Sütun 2 — başlık", def: "Hesap" },
      { key: "footer_col2_l1", label: "Sütun 2 — link 1", def: "Giriş Yap" },
      { key: "footer_col2_l2", label: "Sütun 2 — link 2", def: "Kayıt Ol" },
      { key: "footer_col2_l3", label: "Sütun 2 — link 3", def: "Hesabım" },
      { key: "footer_col2_l4", label: "Sütun 2 — link 4", def: "Randevu Al" },
      { key: "footer_col3_title", label: "Sütun 3 — başlık", def: "Destek" },
      { key: "footer_col3_l1", label: "Sütun 3 — link 1", def: "İletişim" },
      { key: "footer_col3_l2", label: "Sütun 3 — link 2", def: "Kargo & Teslimat" },
      { key: "footer_col3_l3", label: "Sütun 3 — link 3", def: "İade Koşulları" },
      { key: "footer_col3_l4", label: "Sütun 3 — link 4", def: "SSS" },
      { key: "footer_copyright", label: "Telif metni", def: "© Galaksi Motor. Tüm hakları saklıdır." },
      { key: "footer_credit_prefix", label: "Yapım — ön ek", def: "Yapım" },
      { key: "footer_credit_author", label: "Yapım — isim", def: "Galaksi Garage" },
    ],
  },
  {
    title: "WhatsApp Butonu",
    fields: [
      { key: "wa_phone", label: "WhatsApp numarası (ülke koduyla, rakam)", def: "905535732929" },
      { key: "wa_prefill", label: "Hazır mesaj", type: "textarea", def: "Merhaba, Galaksi Motor sitesinden ulaşıyorum." },
      { key: "wa_tooltip_title", label: "Balon başlığı", def: "Yardım lazım mı?" },
      { key: "wa_tooltip_sub", label: "Balon alt metni", def: "WhatsApp'tan dakikalar içinde dönüş." },
    ],
  },
  {
    title: "Randevu Sayfası Metinleri",
    fields: [
      { key: "appt_hero_eyebrow", label: "Üst etiket", def: "Servis Randevusu" },
      { key: "appt_hero_title1", label: "Başlık 1", def: "Motorun için" },
      { key: "appt_hero_title2", label: "Başlık 2 (altın)", def: "randevu al" },
      { key: "appt_hero_desc", label: "Açıklama", type: "textarea", def: "Online randevu sistemiyle sıra beklemeden, dakikalar içinde gününü ayarla." },
      { key: "appt_sec1_title", label: "Adım 1 başlık", def: "Servis seç" },
      { key: "appt_sec2_title", label: "Adım 2 başlık", def: "Tarih seç" },
      { key: "appt_sec3_title", label: "Adım 3 başlık", def: "Saat seç" },
      { key: "appt_sec4_title", label: "Adım 4 başlık", def: "Motor bilgisi (opsiyonel)" },
      { key: "appt_summary_title", label: "Özet başlığı", def: "Randevu Özeti" },
      { key: "appt_btn_confirm", label: "Onay butonu", def: "Randevuyu Onayla" },
      { key: "appt_sms_note", label: "SMS notu", def: "Onaylandığında SMS ile bildireceğiz." },
    ],
  },
  {
    title: "Hesabım & Garaj",
    fields: [
      { key: "account_title", label: "Hesabım başlığı", def: "Hesabım" },
      { key: "account_nav_overview", label: "Menü — Genel Bakış", def: "Genel Bakış" },
      { key: "account_nav_orders", label: "Menü — Siparişlerim", def: "Siparişlerim" },
      { key: "account_nav_appointments", label: "Menü — Randevularım", def: "Randevularım" },
      { key: "account_nav_favorites", label: "Menü — Favorilerim", def: "Favorilerim" },
      { key: "account_nav_garage", label: "Menü — Garajım", def: "🏍 Garajım" },
      { key: "garage_title", label: "Garaj başlığı", def: "Garajım" },
      { key: "garage_subtitle", label: "Garaj alt metni", def: "Motorlarını ekle — sadece sana uygun parçaları gösterelim." },
      { key: "garage_add_btn", label: "Garaj — ekle butonu", def: "+ Motor Ekle" },
      { key: "garage_empty", label: "Garaj — boş metni", def: "Henüz motor eklemedin." },
    ],
  },
];

export const ALL_TEXT_KEYS: string[] = SECTIONS.flatMap((s) => s.fields.map((f) => f.key));
